"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useLanguage } from "@/lib/i18n/LanguageProvider";

const references = [
  { label: "OpenStax Biology 2e", href: "https://openstax.org/details/books/biology-2e" },
  { label: "OpenStax Anatomy & Physiology 2e", href: "https://openstax.org/details/books/anatomy-and-physiology-2e" },
];

function Sources({ biology = true }: { biology?: boolean }) {
  const { lang } = useLanguage();
  const list = biology ? references : references.slice(1);
  return <footer className="mt-8 border-t border-panel-border pt-4 text-xs text-fg-subtle"><span className="font-semibold">{lang === "bn" ? "তথ্যসূত্র:" : "References:"}</span>{" "}{list.map((s, i) => <span key={s.href}>{i ? " · " : ""}<a className="text-accent-2 hover:underline" href={s.href} target="_blank" rel="noreferrer">{s.label}</a></span>)}</footer>;
}

const brainParts = [
  { id: "frontal", en: "Frontal lobe", bn: "ফ্রন্টাল লোব", roleEn: "Planning, voluntary movement, decision-making and aspects of language.", roleBn: "পরিকল্পনা, ঐচ্ছিক নড়াচড়া, সিদ্ধান্ত গ্রহণ ও ভাষার কিছু দিক।", color: "#fb7185" },
  { id: "parietal", en: "Parietal lobe", bn: "প্যারাইটাল লোব", roleEn: "Integrates touch and body-position information and supports spatial attention.", roleBn: "স্পর্শ ও দেহের অবস্থানসংক্রান্ত তথ্য সমন্বয় করে এবং স্থানিক মনোযোগে সহায়তা করে।", color: "#fbbf24" },
  { id: "temporal", en: "Temporal lobe", bn: "টেম্পোরাল লোব", roleEn: "Supports hearing, language comprehension and memory processing.", roleBn: "শ্রবণ, ভাষা বোঝা ও স্মৃতি প্রক্রিয়াকরণে সহায়তা করে।", color: "#60a5fa" },
  { id: "occipital", en: "Occipital lobe", bn: "অক্সিপিটাল লোব", roleEn: "Contains major cortical areas involved in visual processing.", roleBn: "দৃষ্টিসংক্রান্ত তথ্য প্রক্রিয়াকরণে জড়িত প্রধান কর্টিক্যাল অঞ্চল ধারণ করে।", color: "#a78bfa" },
  { id: "cerebellum", en: "Cerebellum", bn: "সেরিবেলাম", roleEn: "Coordinates movement, balance and motor learning.", roleBn: "নড়াচড়ার সমন্বয়, ভারসাম্য ও মোটর শেখায় ভূমিকা রাখে।", color: "#34d399" },
  { id: "brainstem", en: "Brainstem", bn: "ব্রেইনস্টেম", roleEn: "Connects brain and spinal cord and helps regulate vital automatic functions.", roleBn: "মস্তিষ্ক ও সুষুম্নাকাণ্ডকে যুক্ত করে এবং গুরুত্বপূর্ণ স্বয়ংক্রিয় কাজ নিয়ন্ত্রণে সহায়তা করে।", color: "#f97316" },
];

export function BrainExplorer() {
  const { lang } = useLanguage(); const [active, setActive] = useState(brainParts[0].id);
  const part = brainParts.find(x => x.id === active)!;
  return <InteractiveShell title={lang === "bn" ? "প্রধান গঠন নির্বাচন করুন" : "Select a major structure"}>
    <div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]">
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-2">{brainParts.map(p => <button key={p.id} onClick={() => setActive(p.id)} aria-pressed={active === p.id} className={`bio-focus-ring rounded-xl border p-3 text-left text-sm ${active === p.id ? "border-accent bg-accent/10" : "border-panel-border bg-bg-elevated"}`}><span className="mb-2 block h-2 w-8 rounded-full" style={{background:p.color}} />{lang === "bn" ? p.bn : p.en}</button>)}</div>
      <div className="bio-panel rounded-2xl p-5" aria-live="polite"><div className="mb-4 h-32 rounded-[50%_55%_45%_50%] opacity-80" style={{background:`radial-gradient(circle at 35% 35%, ${part.color}, color-mix(in srgb, ${part.color} 35%, transparent))`}} /><h2 className="text-xl font-semibold">{lang === "bn" ? part.bn : part.en}</h2><p className="mt-2 text-fg-muted">{lang === "bn" ? part.roleBn : part.roleEn}</p><p className="mt-4 rounded-xl bg-bg-elevated p-3 text-xs text-fg-subtle">{lang === "bn" ? "এই মানচিত্রটি শিক্ষামূলক সরলীকরণ। বাস্তবে অধিকাংশ মানসিক কাজ বহু সংযুক্ত অঞ্চলের নেটওয়ার্কে সম্পন্ন হয়।" : "This map is an educational simplification. Most mental functions arise from distributed, connected networks rather than a single isolated spot."}</p></div>
    </div><Sources biology={false}/></InteractiveShell>;
}

const microbes = [
  { en:"Red blood cell", bn:"লোহিত রক্তকণিকা", size:7.5, unit:"µm", noteEn:"Carries oxygen using haemoglobin.", noteBn:"হিমোগ্লোবিনের সাহায্যে অক্সিজেন পরিবহন করে।" },
  { en:"Bacterium (E. coli)", bn:"ব্যাকটেরিয়া (E. coli)", size:2, unit:"µm", noteEn:"A typical rod-shaped bacterial length; species vary.", noteBn:"একটি সাধারণ দণ্ডাকার ব্যাকটেরিয়ার দৈর্ঘ্য; প্রজাতিভেদে ভিন্ন হয়।" },
  { en:"Yeast cell", bn:"ইস্ট কোষ", size:6, unit:"µm", noteEn:"A single-celled fungus, commonly several micrometres wide.", noteBn:"এককোষী ছত্রাক; সাধারণত কয়েক মাইক্রোমিটার প্রশস্ত।" },
  { en:"Influenza virus", bn:"ইনফ্লুয়েঞ্জা ভাইরাস", size:0.1, unit:"µm", noteEn:"About 100 nm; far smaller than a cell.", noteBn:"প্রায় ১০০ nm; একটি কোষের চেয়ে অনেক ছোট।" },
];
export function MicroScaleExplorer(){const {lang}=useLanguage();const [i,setI]=useState(0);const item=microbes[i];return <InteractiveShell title={lang==="bn"?"আপেক্ষিক আকার অন্বেষণ":"Explore relative scale"}><input aria-label="Select microscopic object" className="w-full accent-[var(--accent)]" type="range" min="0" max={microbes.length-1} value={i} onChange={e=>setI(+e.target.value)}/><div className="mt-5 grid gap-4 sm:grid-cols-[180px_1fr]"><div className="flex h-44 items-center justify-center rounded-2xl bg-bg-elevated"><div className="rounded-full border-4 border-accent bg-accent/20" style={{width:`${Math.max(18,Math.sqrt(item.size/7.5)*130)}px`,height:`${Math.max(18,Math.sqrt(item.size/7.5)*130)}px`}}/></div><div className="bio-panel rounded-2xl p-5"><h2 className="text-xl font-semibold">{lang==="bn"?item.bn:item.en}</h2><p className="mt-2 text-3xl font-black text-accent">≈ {item.size} {item.unit}</p><p className="mt-3 text-fg-muted">{lang==="bn"?item.noteBn:item.noteEn}</p></div></div><p className="mt-3 text-xs text-fg-subtle">{lang==="bn"?"বৃত্তের ক্ষেত্রফল তুলনা বোঝাতে স্কেল করা; এটি মাইক্রোস্কোপের প্রকৃত ছবি নয়।":"Circle area is scaled to communicate comparison; this is not a microscope image."}</p><Sources/></InteractiveShell>}

const slides={onion:{en:"Onion epidermis",bn:"পেঁয়াজের এপিডার্মিস",color:"#c4b5fd",structures:["Cell wall","Nucleus"]},blood:{en:"Blood smear",bn:"রক্তের স্মিয়ার",color:"#fb7185",structures:["Red blood cells","White blood cell"]},leaf:{en:"Leaf surface",bn:"পাতার পৃষ্ঠ",color:"#4ade80",structures:["Epidermal cells","Stoma"]}};
export function Microscope(){const {lang}=useLanguage();const [slide,setSlide]=useState<keyof typeof slides>("onion");const [mag,setMag]=useState(40);const [focus,setFocus]=useState(65);const s=slides[slide];const blur=Math.abs(focus-65)/10;return <InteractiveShell title={lang==="bn"?"স্লাইড, বিবর্ধন ও ফোকাস নিয়ন্ত্রণ করুন":"Control slide, magnification and focus"}><div className="grid gap-5 lg:grid-cols-[260px_1fr]"><div className="space-y-4"><label className="block text-sm">{lang==="bn"?"স্লাইড":"Slide"}<select className="mt-1 w-full rounded-xl border border-panel-border bg-bg-elevated p-2" value={slide} onChange={e=>setSlide(e.target.value as keyof typeof slides)}>{Object.entries(slides).map(([k,v])=><option key={k} value={k}>{lang==="bn"?v.bn:v.en}</option>)}</select></label><label className="block text-sm">{lang==="bn"?"বিবর্ধন":"Magnification"}<select className="mt-1 w-full rounded-xl border border-panel-border bg-bg-elevated p-2" value={mag} onChange={e=>setMag(+e.target.value)}>{[10,40,100,400].map(v=><option key={v}>{v}</option>)}</select></label><label className="block text-sm">{lang==="bn"?"ফোকাস":"Focus"}<input className="mt-2 w-full accent-[var(--accent)]" type="range" min="0" max="100" value={focus} onChange={e=>setFocus(+e.target.value)}/></label></div><div><div className="relative mx-auto aspect-square max-w-md overflow-hidden rounded-full border-[12px] border-bg-elevated bg-white shadow-inner"><div className="absolute inset-0 grid grid-cols-6 gap-2 p-8 transition-transform" style={{filter:`blur(${blur}px)`,transform:`scale(${1+mag/500})`,background:`radial-gradient(circle, ${s.color}88 0 22%, transparent 24%) 0 0/55px 55px`}}>{Array.from({length:18}).map((_,i)=><span key={i} className="rounded-[45%] border" style={{borderColor:s.color}}/>)}</div></div><p className="mt-3 text-center text-sm text-fg-muted">{lang==="bn"?"শনাক্ত করুন":"Identify"}: {s.structures.join(" · ")}</p></div></div><Sources/></InteractiveShell>}

export function PlantSimulator(){const {lang}=useLanguage();const [light,setLight]=useState(70),[co2,setCo2]=useState(55),[water,setWater]=useState(65);const rate=Math.round(Math.min(light,co2,water));const factors=[{label:lang==="bn"?"আলোর তীব্রতা":"Light intensity",value:light,setter:setLight},{label:"CO₂",value:co2,setter:setCo2},{label:lang==="bn"?"পানির প্রাপ্যতা":"Water availability",value:water,setter:setWater}];return <InteractiveShell title={lang==="bn"?"সালোকসংশ্লেষণের সীমাবদ্ধ উপাদান":"Limiting factors in photosynthesis"}><div className="grid gap-5 md:grid-cols-2"><div className="space-y-5">{factors.map(({label,value,setter})=><label key={label} className="block text-sm">{label}: <b>{value}%</b><input className="mt-2 block w-full accent-[var(--accent)]" type="range" value={value} onChange={e=>setter(+e.target.value)}/></label>)}</div><div className="bio-panel rounded-2xl p-6 text-center"><div className="mx-auto h-36 w-28 rounded-[70%_20%_70%_20%] bg-emerald-500/30 transition-all" style={{filter:`saturate(${.4+rate/70})`,boxShadow:`0 0 ${rate/2}px #34d39955`}}/><p className="mt-4 text-sm text-fg-muted">{lang==="bn"?"আপেক্ষিক সালোকসংশ্লেষণ হার":"Relative photosynthesis rate"}</p><p className="text-4xl font-black text-emerald-500">{rate}%</p><p className="mt-2 text-xs text-fg-subtle">{lang==="bn"?"সবচেয়ে কম প্রাপ্য উপাদানটি এই সরল মডেলে হার সীমিত করে। বাস্তব উদ্ভিদে তাপমাত্রা ও প্রজাতিসহ আরও উপাদান কাজ করে।":"The least available factor limits this simplified model. Real plants are also affected by temperature, species and other conditions."}</p></div></div><Sources/></InteractiveShell>}

export function OsmosisLab(){const {lang}=useLanguage();const [outside,setOutside]=useState(50);const inside=50;const direction=outside>inside?"out":outside<inside?"in":"equal";return <InteractiveShell title={lang==="bn"?"অভিস্রবণ পরীক্ষা":"Osmosis experiment"}><ol className="mb-5 grid gap-2 text-sm sm:grid-cols-3"><li className="bio-panel rounded-xl p-3"><b>1. {lang==="bn"?"উদ্দেশ্য":"Objective"}</b><br/>{lang==="bn"?"ঘনত্বের পার্থক্যে পানির নিট গতি বোঝা।":"Observe net water movement across a selectively permeable membrane."}</li><li className="bio-panel rounded-xl p-3"><b>2. {lang==="bn"?"পরিবর্তন":"Change"}</b><br/>{lang==="bn"?"বাইরের দ্রবণের ঘনত্ব বদলান।":"Adjust outside solute concentration."}</li><li className="bio-panel rounded-xl p-3"><b>3. {lang==="bn"?"পর্যবেক্ষণ":"Observe"}</b><br/>{lang==="bn"?"পানির নিট গতির দিক দেখুন।":"Read the predicted net direction."}</li></ol><label className="text-sm">{lang==="bn"?"বাইরের দ্রব ঘনত্ব":"Outside solute concentration"}: {outside}%<input className="mt-2 block w-full accent-[var(--accent)]" type="range" value={outside} onChange={e=>setOutside(+e.target.value)}/></label><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-4 text-center"><div className="rounded-2xl bg-sky-400/15 p-6">{lang==="bn"?"কোষের বাইরে":"Outside"}<br/><b>{outside}%</b></div><div className="text-3xl text-accent" aria-label="net water direction">{direction==="in"?"→":direction==="out"?"←":"⇄"}</div><div className="rounded-full bg-sky-400/25 p-8">{lang==="bn"?"কোষের ভেতর":"Cell"}<br/><b>{inside}%</b></div></div><p className="mt-4 text-sm text-fg-muted">{lang==="bn"?"উপসংহার: পানি তুলনামূলক কম দ্রব ঘনত্ব থেকে বেশি দ্রব ঘনত্বের দিকে ঝিল্লি অতিক্রম করে নিট চলাচল করে।":"Conclusion: water shows net movement across the membrane from lower solute concentration toward higher solute concentration."}</p><p className="mt-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-xs">{lang==="bn"?"ভার্চুয়াল পরীক্ষা বাস্তব ল্যাব নিরাপত্তা প্রশিক্ষণের বিকল্প নয়।":"Virtual experiments do not replace real laboratory safety training."}</p><Sources/></InteractiveShell>}

export function EcologyExplorer(){const {lang}=useLanguage();const [level,setLevel]=useState(0);const chain=[{en:"Grass",bn:"ঘাস"},{en:"Grasshopper",bn:"ঘাসফড়িং"},{en:"Frog",bn:"ব্যাঙ"},{en:"Snake",bn:"সাপ"}];const energy=Math.round(10000*Math.pow(.1,level));return <InteractiveShell title={lang==="bn"?"খাদ্যশৃঙ্খলে শক্তিপ্রবাহ":"Energy flow through a food chain"}><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{chain.map((x,i)=><button key={x.en} onClick={()=>setLevel(i)} aria-pressed={level===i} className={`bio-focus-ring rounded-2xl border p-4 ${level===i?"border-accent bg-accent/10":"border-panel-border"}`}><span className="block text-2xl font-black text-accent">{i+1}</span>{lang==="bn"?x.bn:x.en}</button>)}</div><div className="mt-5 bio-panel rounded-2xl p-5"><p className="text-sm text-fg-muted">{lang==="bn"?"উদাহরণস্বরূপ উপলভ্য শক্তি":"Illustrative energy available"}</p><p className="text-4xl font-black text-accent">{energy.toLocaleString()} kJ</p><div className="mt-3 h-3 rounded-full bg-bg-elevated"><div className="h-full rounded-full bg-accent" style={{width:`${100*Math.pow(.45,level)}%`}}/></div><p className="mt-3 text-xs text-fg-subtle">{lang==="bn"?"এই শিক্ষামূলক মডেলটি প্রতি ট্রফিক স্তরে প্রায় ১০% শক্তি স্থানান্তরের সাধারণ নিয়ম দেখায়; বাস্তব দক্ষতা পরিবর্তনশীল।":"This teaching model uses the common ~10% trophic-transfer rule; real ecological efficiencies vary."}</p></div><Sources/></InteractiveShell>}

type Progress = Record<string, boolean>;
const progressItems=["Human Body","Cell World","Genetics","Brain Explorer","Micro World","Virtual Microscope","Plant Biology","Virtual Lab","Ecology"];
export function LocalDashboard(){const {lang}=useLanguage();const [progress,setProgress]=useState<Progress>({});useEffect(()=>{const id=window.setTimeout(()=>{try{setProgress(JSON.parse(localStorage.getItem("bioverse-progress")||"{}"))}catch{}},0);return()=>window.clearTimeout(id)},[]);function toggle(x:string){setProgress(p=>{const n={...p,[x]:!p[x]};localStorage.setItem("bioverse-progress",JSON.stringify(n));return n})}const done=progressItems.filter(x=>progress[x]).length;return <InteractiveShell title={lang==="bn"?"আপনার বাস্তব শেখার অগ্রগতি":"Your real learning progress"}><div className="mb-5 rounded-2xl bg-bg-elevated p-5"><p className="text-sm text-fg-muted">{lang==="bn"?"এই ডিভাইসে সম্পন্ন হিসেবে চিহ্নিত":"Marked complete on this device"}</p><p className="text-4xl font-black text-accent">{done}/{progressItems.length}</p></div><div className="grid gap-2 sm:grid-cols-2">{progressItems.map(x=><label key={x} className="bio-panel flex cursor-pointer items-center gap-3 rounded-xl p-3"><input type="checkbox" checked={!!progress[x]} onChange={()=>toggle(x)} className="h-5 w-5 accent-[var(--accent)]"/><span>{x}</span></label>)}</div><p className="mt-4 text-xs text-fg-subtle">{lang==="bn"?"তথ্য শুধু এই ব্রাউজারের local storage-এ থাকে; কোনো অ্যাকাউন্ট বা স্বাস্থ্যতথ্য সংগ্রহ করা হয় না।":"Progress stays in this browser's local storage; no account or health data is collected."}</p></InteractiveShell>}

export function StudyTutor(){const {lang}=useLanguage();const [topic,setTopic]=useState("cell");const answers:{[k:string]:[string,string,string]}={cell:["Cell","কোষ","The basic structural and functional unit of life. Explore organelles and compare cell types."],dna:["DNA","ডিএনএ","The hereditary molecule whose sequence stores biological information."],heart:["Heart","হৃদপিণ্ড","A muscular organ that pumps blood through the circulatory system."]};const dictionaryTarget:{[k:string]:string}={cell:"cell-membrane",dna:"dna",heart:"artery"};const a=answers[topic];return <InteractiveShell title={lang==="bn"?"নিরাপদ BioVerse স্টাডি গাইড":"Safe BioVerse study guide"}><div className="flex flex-wrap gap-2">{Object.keys(answers).map(k=><button key={k} onClick={()=>setTopic(k)} aria-pressed={topic===k} className={`bio-focus-ring rounded-full px-4 py-2 text-sm ${topic===k?"bg-accent text-bg":"bio-panel"}`}>{lang==="bn"?answers[k][1]:answers[k][0]}</button>)}</div><div className="mt-5 bio-panel rounded-2xl p-5" aria-live="polite"><h2 className="text-xl font-semibold">{lang==="bn"?a[1]:a[0]}</h2><p className="mt-2 text-fg-muted">{a[2]}</p><div className="mt-4 flex flex-wrap gap-2"><Link className="rounded-full bg-accent px-4 py-2 text-sm font-semibold text-bg" href={topic==="cell"?"/cell-world":topic==="heart"?"/human-body/heart":"/genetics"}>{lang==="bn"?"ইন্টারঅ্যাক্টিভ পাঠ খুলুন":"Open interactive lesson"}</Link><Link className="rounded-full border border-panel-border px-4 py-2 text-sm" href={`/dictionary/${dictionaryTarget[topic]}`}>{lang==="bn"?"অভিধানে দেখুন":"View dictionary"}</Link></div></div><p className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-xs">{lang==="bn"?"এটি যাচাইকৃত BioVerse বিষয়ভিত্তিক গাইড, রোগ নির্ণয় বা ব্যক্তিগত চিকিৎসা পরামর্শ দেয় না।":"This is a bounded BioVerse topic guide. It does not diagnose conditions or give personal medical advice."}</p><Sources/></InteractiveShell>}

function InteractiveShell({title,children}:{title:string;children:React.ReactNode}){return <section className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><h1 className="mb-6 text-2xl font-bold sm:text-3xl">{title}</h1>{children}</section>}
